version: '3.9'

services:
  # databases
  agregator1:
    image: mysql:8.0
    container_name: mysql_agregator1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agregator1_db
    volumes:
      - ./mysql-agregator1:/docker-entrypoint-initdb.d
      - mysql-ag1-data:/var/lib/mysql
    ports:
      - "3311:3306"

  agregator2:
    image: mysql:8.0
    container_name: mysql_agregator2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agregator2_db
    volumes:
      - ./mysql-agregator2:/docker-entrypoint-initdb.d
      - mysql-ag2-data:/var/lib/mysql
    ports:
      - "3312:3306"

  agregator3:
    image: mysql:8.0
    container_name: mysql_agregator3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agregator3_db
    volumes:
      - ./mysql-agregator3:/docker-entrypoint-initdb.d
      - mysql-ag3-data:/var/lib/mysql
    ports:
      - "3313:3306"

  server:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server-db
    volumes:
      - ./mysql-server:/docker-entrypoint-initdb.d
      - mysql-server-data:/var/lib/mysql
    ports:
      - "3314:3306"

  #agregadores em si
  agregator_app_1:
    build:
        context: ./agregators
        dockerfile: Dockerfile
    container_name: agregator_app_1
    depends_on:
      - agregator1
    environment:
      AGGREGATOR_ID: AGG_01
      MYSQL_HOST: agregator1
      MYSQL_PORT: 3306
      MYSQL_DB: agregator1_db
      MYSQL_USER: root
      MYSQL_PASS: root
      LISTEN_PORT: 13311
      AGG_TOKEN_AGG_01: tokenagr1
    ports:
      - "5001:13311"
    volumes:
      - ./agregators/autorizacoes:/app/autorizacoes

  agregator_app_2:
    build: 
            context: ./agregators
            dockerfile: Dockerfile
    container_name: agregator_app_2
    depends_on:
      - agregator2
    environment:
      AGGREGATOR_ID: AGG_02
      MYSQL_HOST: agregator2
      MYSQL_PORT: 3306
      MYSQL_DB: agregator2_db
      MYSQL_USER: root
      MYSQL_PASS: root
      LISTEN_PORT: 13312
      AGG_TOKEN_AGG_03: tokenagr2
    ports:
      - "5002:13312"
    volumes:
      - ./agregators/autorizacoes:/app/autorizacoes

  agregator_app_3:
    build: 
            context: ./agregators
            dockerfile: Dockerfile
    container_name: agregator_app_3
    depends_on:
      - agregator3
    environment:
      AGGREGATOR_ID: AGG_03
      MYSQL_HOST: agregator3
      MYSQL_PORT: 3306
      MYSQL_DB: agregator3_db
      MYSQL_USER: root
      MYSQL_PASS: root
      LISTEN_PORT: 13313
      AGG_TOKEN_AGG_03: tokenagr3
    ports:
      - "5003:13313"
    volumes:
      - ./agregators/autorizacoes:/app/autorizacoes

  server_app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_app
    depends_on:
      - agregator1
      - agregator2
      - agregator3
      - server
    environment:
        SERVER_PORT: 15000
        AGG_IDS: AGG_01,AGG_02,AGG_03
        MYSQL_HOST_AGG_01: agregator1
        MYSQL_DB_AGG_01: agregator1_db
        MYSQL_HOST_AGG_02: agregator2
        MYSQL_DB_AGG_02: agregator2_db
        MYSQL_HOST_AGG_03: agregator3
        MYSQL_DB_AGG_03: agregator3_db
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASS: root
        MYSQL_HOST_SERVER: server
        MYSQL_DB_SERVER: server-db
        AGG_TOKEN_AGG_01: tokenagr1
        AGG_TOKEN_AGG_02: tokenagr2
        AGG_TOKEN_AGG_03: tokenagr3
    ports:
        - "5004:15000"


volumes:
  mysql-ag1-data:
  mysql-ag2-data:
  mysql-ag3-data:
  mysql-server-data:
